# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hnews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='voter',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-rank_is_expired', '-hn_rank']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank',
        ),
        migrations.AddField(
            model_name='post',
            name='hn_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hn_rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
